split_date: "2023-01-01"
features:
  - ret_pct
  - sma_7
  - sma_20
  - ema_12
  - ema_26
  - rsi_14
  - atr_14
  - adx_14
  - bb_ma_20_2
  - bb_u_20_2
  - bb_l_20_2
  - volume
  - trades
  - sma_spread_7_20
  - ema_spread_12_26
